siteTitle: Emabook
theme: blue
# <with var="custom"> ...
custom:
  # <value:rawHtml />
  foo: red
  # <with var="bar"> ...
  bar: ["hello", "world"]
  # <snippet:rawHtml />
  rawHtml: "<b>Ema</b> is <u>cool</u>!"