[formatter.haskell]
command = "ormolu"
options = [
    "--ghc-opt", "-XImportQualifiedPost",
    "--ghc-opt", "-XTypeApplications",
    "--mode", "inplace",
    "--check-idempotence",
]
includes = ["*.hs"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]