name: "CI"

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  nix:
    runs-on: self-hosted
    strategy:
      matrix:
        # TODO: Disabling x86_64-linux for now, as it is causing qemu segfault.
        # Fix treefmt check causing qemu segfault: https://nixos.zulipchat.com/#narrow/stream/413948-nixos/topic/QEMU.20internal.20SIGSEGV
        system: [aarch64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - name: Build Nix
        run: |
          nixci --build-systems "github:nix-systems/${{ matrix.system }}"
      - name: Check closure size
        run: |
          nix run .#check-closure-size

  # TODO: Use self-hosted runner
  website:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io?priority=41 https://cache.nixos.org/
      - name: Docs static site
        id: docs
        run: |
          nix build .#docs -o docs-static
          if ! [ -f ./docs-static/index.html ]; then
            echo "ERROR: There is no index.html"
            exit 2
          fi
      - name: Deploy docs to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-static
          cname: emanote.srid.ca
